### ISSUE TITLE
SourceInjector hdf file format issue

### ISSUE THREAD

**Issue by parshadkp** [cositools/cosipy#272]
I want to create a new file adding all counts from an .hdf5 using a source generated with SourceInjector and the background used in crab_binned_data.hdf5. I'm having the issue with the two files having different shapes. How can I fix this? 

inject_point_source in sourceInjector seems to create a .hdf5 file with a different shape than the regular format from crab_binned_data.hdf5. 

Source Injector file has shape:
/hist/axes/0: (11,)
/hist/axes/1: (37,)
/hist/axes/2: (769,)
/hist/contents: (12, 38, 770)

crab_binned_data.hdf5 has shape:
/hist/axes/0: (2218,)
/hist/axes/1: (11,)
/hist/axes/2: (37,)
/hist/axes/3: (769,)
/hist/contents/coords: (4, 45332366)
/hist/contents/data: (45332366,)
/hist/contents/fill_value: ()
/hist/contents/shape: (4,)

**Comment by Yong2Sheng** [comment]
Hi @parshadkp, the axes of the data you generated using the source injector only contains three axes:
- Energy, 10 bins
- Compton scattering angle: 36 bins
- PsiChi: 768 bins

The data generated by the simulations has one more axes, which is the time axis.
 The current analysis is not time dependent, so we can just flatten the time axes by runing:
```
>>> from histpy import Histogram
>>> hist = Histogram.open("crab_binned_data.hdf5")
>>> hist.axes.labels
>>> new_hist = hist.project(['Em', 'Phi', 'PsiChi'])
>>> new_hist.axes.labels
```
After that, you can do binary operations on the `histpy.Histogram` objects like this:
```
>>> total = src_hist + bkg_hist
```

***Something to notice***
You might encounter an error saying that the energy axes mismatch, which is caused by the different axis scales in the injected and simulated data. You can simply reset the energy scale of the injected data by running this:
```
>>> new_hist.axes["Em"].axis_scale = "log"
```

**Comment by parshadkp** [comment]
Hi @Yong2Sheng, I want to add the two .hdf5 directly to use for spectral fitting like the SpectralFit_Crab notebook. Is that possible?

**Comment by Yong2Sheng** [comment]
Hi @parshadkp, yes you can do that. As long as the axes of the two files match. What files are you adding up?

**Comment by parshadkp** [comment]
It doesn't look like the axes match up. As you said, there is a n extra time axes in the .hdf5 from the simulation. I want to add up the counts from the sourceInjector file to the counts from the bkg_binned_data.hdf5 from the Crab spectral fitting example.

**Comment by Yong2Sheng** [comment]
This issue has been solved by the Slack conversation with @parshadkp. 

@parshadkp reported a bug that the injected data has unit of $cm^2/s/keV$ instead of `None` or `cts`. I will open a new issue to fix this.
